In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import rcParams
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(r"C:\Users\sheet\Dataset\data_Q2_2022\dataq2.csv",encoding='utf-8',header=0)
df.head()

,Unnamed: 0,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
0,0,2022-06-30,PL1331LAGSMWSH,HGST HMS5C4040ALE640,4000787030016,0,100.0,0.0,134.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2022-06-30,PL2331LAGSSWKJ,HGST HMS5C4040ALE640,4000787030016,0,100.0,0.0,133.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2022-06-30,PL2331LAGSU9VJ,HGST HMS5C4040ALE640,4000787030016,0,100.0,0.0,133.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2022-06-30,ZA1JWY0B,ST8000NM0055,8001563222016,0,84.0,243517744.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2022-06-30,PL2331LAGSST6J,HGST HMS5C4040ALE640,4000787030016,0,100.0,0.0,134.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
filter_col = [col for col in df if col.endswith('_raw')]
filter_col

['smart_1_raw',
 'smart_2_raw',
 'smart_3_raw',
 'smart_4_raw',
 'smart_5_raw',
 'smart_7_raw',
 'smart_8_raw',
 'smart_9_raw',
 'smart_10_raw',
 'smart_11_raw',
 'smart_12_raw',
 'smart_13_raw',
 'smart_15_raw',
 'smart_16_raw',
 'smart_17_raw',
 'smart_18_raw',
 'smart_22_raw',
 'smart_23_raw',
 'smart_24_raw',
 'smart_160_raw',
 'smart_161_raw',
 'smart_163_raw',
 'smart_164_raw',
 'smart_165_raw',
 'smart_166_raw',
 'smart_167_raw',
 'smart_168_raw',
 'smart_169_raw',
 'smart_170_raw',
 'smart_171_raw',
 'smart_172_raw',
 'smart_173_raw',
 'smart_174_raw',
 'smart_175_raw',
 'smart_176_raw',
 'smart_177_raw',
 'smart_178_raw',
 'smart_179_raw',
 'smart_180_raw',
 'smart_181_raw',
 'smart_182_raw',
 'smart_183_raw',
 'smart_184_raw',
 'smart_187_raw',
 'smart_188_raw',
 'smart_189_raw',
 'smart_190_raw',
 'smart_191_raw',
 'smart_192_raw',
 'smart_193_raw',
 'smart_194_raw',
 'smart_195_raw',
 'smart_196_raw',
 'smart_197_raw',
 'smart_198_raw',
 'smart_199_raw',
 'smart_200_raw',
 'smart_201_raw',
 'smart_202_raw',
 'smart_206_raw',
 'smart_210_raw',
 'smart_218_raw',
 'smart_220_raw',
 'smart_222_raw',
 'smart_223_raw',
 'smart_224_raw',
 'smart_225_raw',
 'smart_226_raw',
 'smart_230_raw',
 'smart_231_raw',
 'smart_232_raw',
 'smart_233_raw',
 'smart_234_raw',
 'smart_235_raw',
 'smart_240_raw',
 'smart_241_raw',
 'smart_242_raw',
 'smart_244_raw',
 'smart_245_raw',
 'smart_246_raw',
 'smart_247_raw',
 'smart_248_raw',
 'smart_250_raw',
 'smart_251_raw',
 'smart_252_raw',
 'smart_254_raw',
 'smart_255_raw']

In [4]:
data1 = df.drop(columns= filter_col)

In [5]:
data1.head()

,Unnamed: 0,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_2_normalized,smart_3_normalized,smart_4_normalized,...,smart_244_normalized,smart_245_normalized,smart_246_normalized,smart_247_normalized,smart_248_normalized,smart_250_normalized,smart_251_normalized,smart_252_normalized,smart_254_normalized,smart_255_normalized
0,0,2022-06-30,PL1331LAGSMWSH,HGST HMS5C4040ALE640,4000787030016,0,100.0,134.0,136.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2022-06-30,PL2331LAGSSWKJ,HGST HMS5C4040ALE640,4000787030016,0,100.0,133.0,141.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2022-06-30,PL2331LAGSU9VJ,HGST HMS5C4040ALE640,4000787030016,0,100.0,133.0,138.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2022-06-30,ZA1JWY0B,ST8000NM0055,8001563222016,0,84.0,NaN,95.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2022-06-30,PL2331LAGSST6J,HGST HMS5C4040ALE640,4000787030016,0,100.0,134.0,137.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#missing values 

nan_in_df = data1.isnull().sum().sum()
print('Number of NaN values present: ' + str(nan_in_df))
df2=data1.fillna(0)

Number of NaN values present: 8778966

In [7]:
def feature_corr(df, threshold):

    corr = pd.DataFrame(abs(df.corr()))

    Featurei = []
    Featurej = []
    Corr = []

    for i in corr.index:
        for j in corr.columns:
            if (corr.loc[i, j] > threshold and i != j):
                if(i not in Featurei):
                    Featurei.append(i)
                if(j not in Featurej):
                    Featurej.append(j)
                    Corr.append(corr.loc[i, j])
    
    d = pd.DataFrame([Featurei, Featurej, Corr]).transpose()
    display(d)
    highly_correlated = set(d[0])
    
    print('Number of features = ', len(highly_correlated))

In [8]:
corr_data = feature_corr(df2,0.0)

                       0                     1         2
0             Unnamed: 0        capacity_bytes  0.020959
1         capacity_bytes               failure  0.067113
2                failure    smart_1_normalized  0.029469
3     smart_1_normalized    smart_2_normalized  0.017824
4     smart_2_normalized    smart_3_normalized  0.004343
..                   ...                   ...       ...
66  smart_240_normalized  smart_241_normalized  0.016743
67  smart_241_normalized  smart_242_normalized  0.016743
68  smart_242_normalized  smart_245_normalized  0.014099
69  smart_245_normalized  smart_254_normalized  0.004478
70  smart_254_normalized            Unnamed: 0  0.020959

[71 rows x 3 columns]

Number of features =  71

In [9]:
corr_data = feature_corr(df2,0.8)

                       0                     1         2
0     smart_2_normalized    smart_8_normalized  0.996408
1     smart_4_normalized  smart_188_normalized  0.928604
2     smart_5_normalized  smart_190_normalized  0.914883
3     smart_7_normalized  smart_194_normalized  0.829245
4     smart_8_normalized  smart_196_normalized  0.957748
5    smart_10_normalized  smart_241_normalized  0.934009
6    smart_11_normalized  smart_242_normalized  0.934009
7    smart_13_normalized   smart_16_normalized  0.886103
8    smart_16_normalized   smart_17_normalized  0.886103
9    smart_17_normalized  smart_168_normalized  0.900172
10   smart_18_normalized  smart_170_normalized  0.900172
11   smart_23_normalized  smart_173_normalized  0.900172
12   smart_24_normalized  smart_174_normalized  0.900172
13  smart_165_normalized  smart_199_normalized  0.906938
14  smart_166_normalized  smart_218_normalized  0.886103
15  smart_167_normalized  smart_231_normalized  0.886103
16  smart_168_normalized  smart_232_normalized  0.900172
17  smart_169_normalized  smart_233_normalized  0.958954
18  smart_170_normalized  smart_235_normalized  0.886103
19  smart_171_normalized    smart_7_normalized  0.819601
20  smart_172_normalized   smart_10_normalized  0.837171
21  smart_173_normalized    smart_5_normalized  0.819601
22  smart_174_normalized    smart_2_normalized  0.996408
23  smart_179_normalized  smart_198_normalized  0.817939
24  smart_181_normalized  smart_225_normalized   0.80731
25  smart_182_normalized  smart_179_normalized       1.0
26  smart_184_normalized  smart_181_normalized       1.0
27  smart_187_normalized  smart_182_normalized       1.0
28  smart_188_normalized  smart_201_normalized       1.0
29  smart_189_normalized  smart_202_normalized  0.999987
30  smart_190_normalized  smart_245_normalized  0.999987
31  smart_194_normalized    smart_4_normalized  0.886103
32  smart_196_normalized  smart_200_normalized  0.897455
33  smart_198_normalized   smart_24_normalized  0.999927
34  smart_199_normalized  smart_220_normalized   0.91338
35  smart_200_normalized  smart_222_normalized  0.938439
36  smart_201_normalized  smart_223_normalized  0.881013
37  smart_202_normalized  smart_224_normalized   0.91338
38  smart_218_normalized  smart_226_normalized   0.91338
39  smart_220_normalized   smart_23_normalized  0.999927
40  smart_222_normalized  smart_166_normalized       1.0
41  smart_223_normalized  smart_167_normalized       1.0
42  smart_224_normalized  smart_169_normalized       1.0
43  smart_225_normalized  smart_171_normalized       1.0
44  smart_226_normalized  smart_172_normalized       1.0
45  smart_230_normalized  smart_230_normalized  0.987569
46  smart_231_normalized  smart_165_normalized       1.0
47  smart_232_normalized   smart_13_normalized       1.0
48  smart_233_normalized  smart_189_normalized  0.987974
49  smart_235_normalized  smart_187_normalized  0.858564
50  smart_241_normalized  smart_184_normalized  0.987974
51  smart_242_normalized   smart_18_normalized  0.897455
52  smart_245_normalized   smart_11_normalized   0.80731

Number of features =  53

In [10]:
corr_data = feature_corr(df2,0.9)

                       0                     1         2
0     smart_2_normalized    smart_8_normalized  0.996408
1     smart_4_normalized  smart_188_normalized  0.928604
2     smart_8_normalized  smart_190_normalized  0.914883
3    smart_13_normalized  smart_196_normalized  0.957748
4    smart_16_normalized  smart_241_normalized  0.934009
5    smart_17_normalized  smart_242_normalized  0.934009
6    smart_23_normalized  smart_168_normalized  0.900172
7    smart_24_normalized  smart_170_normalized  0.900172
8   smart_165_normalized  smart_173_normalized  0.900172
9   smart_166_normalized  smart_174_normalized  0.900172
10  smart_167_normalized  smart_199_normalized  0.906938
11  smart_168_normalized  smart_232_normalized  0.900172
12  smart_169_normalized  smart_233_normalized  0.958954
13  smart_170_normalized    smart_2_normalized  0.996408
14  smart_171_normalized  smart_179_normalized       1.0
15  smart_172_normalized  smart_181_normalized       1.0
16  smart_173_normalized  smart_182_normalized       1.0
17  smart_174_normalized  smart_201_normalized       1.0
18  smart_179_normalized  smart_202_normalized  0.999987
19  smart_181_normalized  smart_245_normalized  0.999987
20  smart_182_normalized   smart_17_normalized       1.0
21  smart_184_normalized  smart_218_normalized       1.0
22  smart_188_normalized  smart_231_normalized       1.0
23  smart_189_normalized  smart_235_normalized       1.0
24  smart_190_normalized   smart_16_normalized       1.0
25  smart_196_normalized   smart_24_normalized  0.999927
26  smart_199_normalized  smart_220_normalized   0.91338
27  smart_201_normalized  smart_222_normalized  0.938439
28  smart_202_normalized  smart_224_normalized   0.91338
29  smart_218_normalized  smart_226_normalized   0.91338
30  smart_220_normalized   smart_23_normalized  0.999927
31  smart_222_normalized  smart_166_normalized       1.0
32  smart_223_normalized  smart_167_normalized       1.0
33  smart_224_normalized  smart_169_normalized       1.0
34  smart_226_normalized  smart_171_normalized       1.0
35  smart_230_normalized  smart_172_normalized       1.0
36  smart_231_normalized  smart_230_normalized  0.987569
37  smart_232_normalized  smart_165_normalized       1.0
38  smart_233_normalized    smart_4_normalized  0.900172
39  smart_235_normalized   smart_13_normalized       1.0
40  smart_241_normalized  smart_189_normalized  0.987974
41  smart_242_normalized  smart_184_normalized  0.987974
42  smart_245_normalized  smart_223_normalized  0.964871

Number of features =  43

In [11]:
corr_data = feature_corr(df2,0.99)

                       0                     1         2
0     smart_2_normalized    smart_8_normalized  0.996408
1     smart_8_normalized    smart_2_normalized  0.996408
2    smart_13_normalized  smart_179_normalized       1.0
3    smart_16_normalized  smart_181_normalized       1.0
4    smart_17_normalized  smart_182_normalized       1.0
5    smart_23_normalized  smart_201_normalized       1.0
6    smart_24_normalized  smart_202_normalized  0.999987
7   smart_165_normalized  smart_245_normalized  0.999987
8   smart_166_normalized   smart_17_normalized       1.0
9   smart_167_normalized  smart_218_normalized       1.0
10  smart_168_normalized  smart_231_normalized       1.0
11  smart_169_normalized  smart_235_normalized       1.0
12  smart_170_normalized   smart_16_normalized       1.0
13  smart_171_normalized   smart_24_normalized  0.999927
14  smart_172_normalized   smart_23_normalized  0.999927
15  smart_173_normalized  smart_166_normalized       1.0
16  smart_174_normalized  smart_167_normalized       1.0
17  smart_179_normalized  smart_169_normalized       1.0
18  smart_181_normalized  smart_171_normalized       1.0
19  smart_182_normalized  smart_172_normalized       1.0
20  smart_201_normalized  smart_165_normalized       1.0
21  smart_202_normalized  smart_170_normalized       1.0
22  smart_218_normalized  smart_173_normalized       1.0
23  smart_220_normalized  smart_174_normalized       1.0
24  smart_224_normalized  smart_232_normalized       1.0
25  smart_226_normalized  smart_168_normalized       1.0
26  smart_231_normalized   smart_13_normalized       1.0
27  smart_232_normalized  smart_224_normalized       1.0
28  smart_235_normalized  smart_226_normalized       1.0
29  smart_241_normalized  smart_220_normalized       1.0
30  smart_242_normalized  smart_242_normalized       1.0
31  smart_245_normalized  smart_241_normalized       1.0

Number of features =  32

In [12]:
#for classification problem

# establish target and features of the data
# set the target to the failure column
y = df2[['failure']]
# set the features as the rest of the dataset after dropping the features that are no
X = df2.drop(['failure','date','serial_number','model','capacity_bytes','Unnamed: 0'], axis=1)
##get train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [13]:
from boruta import BorutaPy
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=1, n_estimators=1000, max_depth=5)
boruta_selector = BorutaPy(rfc, n_estimators='auto', verbose=2, random_state=1)
boruta_selector.fit(np.array(X_train), np.array(y_train))

C:\Users\sheet\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sheet\anaconda3\lib\site-packages\boruta\boruta_py.py:384: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator.fit(X, y)

Iteration: 	1 / 100
Confirmed: 	0
Tentative: 	87
Rejected: 	0

C:\Users\sheet\anaconda3\lib\site-packages\boruta\boruta_py.py:384: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator.fit(X, y)

Iteration: 	2 / 100
Confirmed: 	0
Tentative: 	87
Rejected: 	0

C:\Users\sheet\anaconda3\lib\site-packages\boruta\boruta_py.py:384: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator.fit(X, y)

Iteration: 	3 / 100
Confirmed: 	0
Tentative: 	87
Rejected: 	0

C:\Users\sheet\anaconda3\lib\site-packages\boruta\boruta_py.py:384: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator.fit(X, y)

Iteration: 	4 / 100
Confirmed: 	0
Tentative: 	87
Rejected: 	0

C:\Users\sheet\anaconda3\lib\site-packages\boruta\boruta_py.py:384: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator.fit(X, y)

Iteration: 	5 / 100
Confirmed: 	0
Tentative: 	87
Rejected: 	0

C:\Users\sheet\anaconda3\lib\site-packages\boruta\boruta_py.py:384: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator.fit(X, y)

Iteration: 	6 / 100
Confirmed: 	0
Tentative: 	87
Rejected: 	0

C:\Users\sheet\anaconda3\lib\site-packages\boruta\boruta_py.py:384: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator.fit(X, y)

Iteration: 	7 / 100
Confirmed: 	0
Tentative: 	87
Rejected: 	0

C:\Users\sheet\anaconda3\lib\site-packages\boruta\boruta_py.py:384: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator.fit(X, y)

Iteration: 	8 / 100
Confirmed: 	8
Tentative: 	0
Rejected: 	79


BorutaPy finished running.

Iteration: 	9 / 100
Confirmed: 	8
Tentative: 	0
Rejected: 	79

BorutaPy(estimator=RandomForestClassifier(max_depth=5, n_estimators=263,
                                          random_state=RandomState(MT19937) at 0x226455D6840),
         n_estimators='auto',
         random_state=RandomState(MT19937) at 0x226455D6840, verbose=2)

In [14]:
# Ranking of Boruta

print("Ranking: ",boruta_selector.ranking_)          
print("No. of significant features: ", boruta_selector.n_features_)

Ranking:  [ 1 11  3 23  1  2 12  1 26 47  1 43 71 40 38 14 46 37 27 71 71 71 71 56
 53 61 30 56 35 59 58 27 29 71 71 60 71 51 71 43 39 16 19  1  8 18  3 10
  5  6  1  6 21  1  1 13 17 50 47 71 71 32 45  8 34 42 30 49 56 35 25 14
 54 33 21 21 23 71 41 71 71 71 71 71 71 52 71]
No. of significant features:  8

In [15]:
accepted = X_train.columns[boruta_selector.support_].to_list()

undecided = X_train.columns[boruta_selector.support_weak_].to_list()

selected_features = accepted + undecided


print(selected_features)

['smart_1_normalized', 'smart_5_normalized', 'smart_9_normalized', 'smart_12_normalized', 'smart_187_normalized', 'smart_194_normalized', 'smart_197_normalized', 'smart_198_normalized']

In [16]:
len(selected_features)

8

In [17]:
selected_rf_features = pd.DataFrame({'Feature':list(X_train.columns),
                                       'Ranking':boruta_selector.ranking_})
selected_rf_features.sort_values(by='Ranking').head(10)

                 Feature  Ranking
0     smart_1_normalized        1
54  smart_198_normalized        1
53  smart_197_normalized        1
50  smart_194_normalized        1
10   smart_12_normalized        1
7     smart_9_normalized        1
43  smart_187_normalized        1
4     smart_5_normalized        1
5     smart_7_normalized        2
2     smart_3_normalized        3

In [20]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
#from sklearn.metrics import scorer
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.model_selection import GridSearchCV 
from sklearn.model_selection import RandomizedSearchCV

classifiers = [['Naive Bayes :', GaussianNB()],
               ['KNeighbours :', KNeighborsClassifier()],
               ['SVM :', SVC()],
               ['LogisticRegression :', LogisticRegression()],
               ['DecisionTree :',DecisionTreeClassifier()],
               ['RandomForest :',RandomForestClassifier()]]

for name,classifier in classifiers:
    clf=classifier.fit(X_train,y_train)
    y_pred=classifier.predict(X_test)
    print(f'\n {name} \n')
    print(f'Training Score for {name}  {clf.score(X_train,y_train) * 100:.2f}' )
    print(f'Testing Score for {name} {clf.score(X_test,y_test) * 100:.2f}' )
    print(f'Classification report  \n {classification_report(y_test,y_pred)}' )
    print(f'Confusion matrix  \n {confusion_matrix(y_test,y_pred)}' )
    print(f'ROC AUC  : {roc_auc_score(y_test,y_pred)}' )
    tn, fp, fn, tp = confusion_matrix(y_test,y_pred).ravel()
    print('sensitivity is %f',1.*tp/(tp+fn))
    print('specificity is %f',1.*tn/(tn+fp))
    print('accuracy is %f',1.*(tp+tn)/(tp+tn+fp+fn))
    print('balanced accuracy is %',1./2*(1.*tp/(tp+fn)+1.*tn/(tn+fp)))
    print('Type1 Error is %f',1.*(fp))
    print('Type2 Error is %f',1.*(fn))

 Naive Bayes :

Training Score for Naive Bayes :  1.52
Testing Score for Naive Bayes : 1.54
Classification report
               precision    recall  f1-score   support

           0       0.98      0.01      0.01     27257
           1       0.01      0.99      0.02       280

    accuracy                           0.02     27537
   macro avg       0.50      0.50      0.02     27537
weighted avg       0.97      0.02      0.01     27537

Confusion matrix
 [[  148 27109]
 [    3   277]]
ROC AUC  : 0.49735775606790394
sensitivity is %f 0.9892857142857143
specificity is %f 0.005429797850093554
accuracy is %f 0.015433780005084068
balanced accuracy is % 0.49735775606790394
Type1 Error is %f 27109.0
Type2 Error is %f 3.0

 KNeighbours :

Training Score for KNeighbours :  98.93
Testing Score for KNeighbours : 98.97
Classification report
               precision    recall  f1-score   support

           0       0.99      1.00      0.99     27257
           1       0.17      0.00      0.01       280

    accuracy                           0.99     27537
   macro avg       0.58      0.50      0.50     27537
weighted avg       0.98      0.99      0.98     27537

Confusion matrix
 [[27252     5]
 [  279     1]]
ROC AUC  : 0.5016939947274357
sensitivity is %f 0.0035714285714285713
specificity is %f 0.9998165608834428
accuracy is %f 0.9896866034789555
balanced accuracy is % 0.5016939947274357
Type1 Error is %f 5.0
Type2 Error is %f 279.0

 SVM :

Training Score for SVM :  98.93
Testing Score for SVM : 98.98
Classification report
               precision    recall  f1-score   support

           0       0.99      1.00      0.99     27257
           1       0.00      0.00      0.00       280

    accuracy                           0.99     27537
   macro avg       0.49      0.50      0.50     27537
weighted avg       0.98      0.99      0.98     27537

Confusion matrix
 [[27257     0]
 [  280     0]]
ROC AUC  : 0.5
sensitivity is %f 0.0
specificity is %f 1.0
accuracy is %f 0.9898318625848858
balanced accuracy is % 0.5
Type1 Error is %f 0.0
Type2 Error is %f 280.0

 LogisticRegression :

Training Score for LogisticRegression :  98.93
Testing Score for LogisticRegression : 98.98
Classification report
               precision    recall  f1-score   support

           0       0.99      1.00      0.99     27257
           1       0.00      0.00      0.00       280

    accuracy                           0.99     27537
   macro avg       0.49      0.50      0.50     27537
weighted avg       0.98      0.99      0.98     27537

Confusion matrix
 [[27257     0]
 [  280     0]]
ROC AUC  : 0.5
sensitivity is %f 0.0
specificity is %f 1.0
accuracy is %f 0.9898318625848858
balanced accuracy is % 0.5
Type1 Error is %f 0.0
Type2 Error is %f 280.0

 DecisionTree :

Training Score for DecisionTree :  99.57
Testing Score for DecisionTree : 98.35
Classification report
               precision    recall  f1-score   support

           0       0.99      0.99      0.99     27257
           1       0.04      0.03      0.03       280

    accuracy                           0.98     27537
   macro avg       0.52      0.51      0.51     27537
weighted avg       0.98      0.98      0.98     27537

Confusion matrix
 [[27074   183]
 [  272     8]]
ROC AUC  : 0.5109287784527172
sensitivity is %f 0.02857142857142857
specificity is %f 0.993286128334006
accuracy is %f 0.9834767767004394
balanced accuracy is % 0.5109287784527172
Type1 Error is %f 183.0
Type2 Error is %f 272.0

 RandomForest :

Training Score for RandomForest :  99.57
Testing Score for RandomForest : 98.83
Classification report
               precision    recall  f1-score   support

           0       0.99      1.00      0.99     27257
           1       0.02      0.00      0.01       280

    accuracy                           0.99     27537
   macro avg       0.51      0.50      0.50     27537
weighted avg       0.98      0.99      0.98     27537

Confusion matrix
 [[27214    43]
 [  279     1]]
ROC AUC  : 0.5009969260845183
sensitivity is %f 0.0035714285714285713
specificity is %f 0.9984224235976079
accuracy is %f 0.9883066419726186
balanced accuracy is % 0.5009969260845183
Type1 Error is %f 43.0
Type2 Error is %f 279.0

In [21]:
#Applying selected features and training the model

In [22]:
X_Filtered_train = X_train[selected_features]
X_Filtered_test =  X_test[selected_features]

In [23]:
X_Filtered_train.head()

,smart_1_normalized,smart_5_normalized,smart_9_normalized,smart_12_normalized,smart_187_normalized,smart_194_normalized,smart_197_normalized,smart_198_normalized
34292,79.0,100.0,83.0,100.0,97.0,46.0,100.0,100.0
55036,106.0,100.0,36.0,100.0,100.0,20.0,100.0,100.0
56380,81.0,100.0,81.0,100.0,100.0,36.0,100.0,100.0
50208,80.0,100.0,78.0,100.0,100.0,22.0,100.0,100.0
81131,100.0,100.0,93.0,100.0,0.0,214.0,100.0,100.0

In [24]:
X_Filtered_test .head()

,smart_1_normalized,smart_5_normalized,smart_9_normalized,smart_12_normalized,smart_187_normalized,smart_194_normalized,smart_197_normalized,smart_198_normalized
114876,100.0,100.0,94.0,100.0,0.0,250.0,100.0,100.0
121920,83.0,100.0,81.0,100.0,99.0,26.0,100.0,100.0
4004,76.0,100.0,51.0,100.0,100.0,34.0,100.0,100.0
102516,83.0,100.0,54.0,100.0,100.0,40.0,100.0,100.0
96494,93.0,100.0,93.0,100.0,0.0,240.0,100.0,100.0

In [26]:
classifiers = [['Naive Bayes :', GaussianNB()],
               ['KNeighbours :', KNeighborsClassifier()],
               ['SVM :', SVC()],
               ['LogisticRegression :', LogisticRegression()],
               ['DecisionTree :',DecisionTreeClassifier()],
               ['RandomForest :',RandomForestClassifier()]]

for name,classifier in classifiers:
    clf=classifier.fit(X_Filtered_train,y_train)
    y_pred1=classifier.predict(X_Filtered_test)
    print(f'\n {name} \n')
    print(f'Training Score for {name}  {clf.score(X_Filtered_train,y_train) * 100:.2f}' )
    print(f'Testing Score for {name} {clf.score(X_Filtered_test,y_test) * 100:.2f}' )
    print(f'Classification report  \n {classification_report(y_test,y_pred1)}' )
    print(f'Confusion matrix  \n {confusion_matrix(y_test,y_pred1)}' )
    print(f'ROC AUC  : {roc_auc_score(y_test,y_pred1)}' )
    tn, fp, fn, tp = confusion_matrix(y_test,y_pred1).ravel()
    print('sensitivity is %f',1.*tp/(tp+fn))
    print('specificity is %f',1.*tn/(tn+fp))
    print('accuracy is %f',1.*(tp+tn)/(tp+tn+fp+fn))
    print('balanced accuracy is %',1./2*(1.*tp/(tp+fn)+1.*tn/(tn+fp)))
    print('Type1 Error is %f',1.*(fp))
    print('Type2 Error is %f',1.*(fn))

 Naive Bayes :

Training Score for Naive Bayes :  96.74
Testing Score for Naive Bayes : 96.86
Classification report
               precision    recall  f1-score   support

           0       0.99      0.98      0.98     27257
           1       0.02      0.04      0.02       280

    accuracy                           0.97     27537
   macro avg       0.50      0.51      0.50     27537
weighted avg       0.98      0.97      0.97     27537

Confusion matrix
 [[26662   595]
 [  270    10]]
ROC AUC  : 0.5069425154219886
sensitivity is %f 0.03571428571428571
specificity is %f 0.9781707451296915
accuracy is %f 0.9685877183425936
balanced accuracy is % 0.5069425154219886
Type1 Error is %f 595.0
Type2 Error is %f 270.0

 KNeighbours :

Training Score for KNeighbours :  98.93
Testing Score for KNeighbours : 98.98
Classification report
               precision    recall  f1-score   support

           0       0.99      1.00      0.99     27257
           1       0.43      0.01      0.02       280

    accuracy                           0.99     27537
   macro avg       0.71      0.51      0.51     27537
weighted avg       0.98      0.99      0.98     27537

Confusion matrix
 [[27253     4]
 [  277     3]]
ROC AUC  : 0.5052837672105199
sensitivity is %f 0.010714285714285714
specificity is %f 0.9998532487067542
accuracy is %f 0.9897955478084033
balanced accuracy is % 0.5052837672105199
Type1 Error is %f 4.0
Type2 Error is %f 277.0

 SVM :

Training Score for SVM :  98.93
Testing Score for SVM : 98.98
Classification report
               precision    recall  f1-score   support

           0       0.99      1.00      0.99     27257
           1       0.00      0.00      0.00       280

    accuracy                           0.99     27537
   macro avg       0.49      0.50      0.50     27537
weighted avg       0.98      0.99      0.98     27537

Confusion matrix
 [[27257     0]
 [  280     0]]
ROC AUC  : 0.5
sensitivity is %f 0.0
specificity is %f 1.0
accuracy is %f 0.9898318625848858
balanced accuracy is % 0.5
Type1 Error is %f 0.0
Type2 Error is %f 280.0

 LogisticRegression :

Training Score for LogisticRegression :  98.93
Testing Score for LogisticRegression : 98.98
Classification report
               precision    recall  f1-score   support

           0       0.99      1.00      0.99     27257
           1       0.00      0.00      0.00       280

    accuracy                           0.99     27537
   macro avg       0.49      0.50      0.50     27537
weighted avg       0.98      0.99      0.98     27537

Confusion matrix
 [[27257     0]
 [  280     0]]
ROC AUC  : 0.5
sensitivity is %f 0.0
specificity is %f 1.0
accuracy is %f 0.9898318625848858
balanced accuracy is % 0.5
Type1 Error is %f 0.0
Type2 Error is %f 280.0

 DecisionTree :

Training Score for DecisionTree :  99.41
Testing Score for DecisionTree : 98.58
Classification report
               precision    recall  f1-score   support

           0       0.99      1.00      0.99     27257
           1       0.07      0.03      0.04       280

    accuracy                           0.99     27537
   macro avg       0.53      0.51      0.52     27537
weighted avg       0.98      0.99      0.98     27537

Confusion matrix
 [[27138   119]
 [  271     9]]
ROC AUC  : 0.5138885030843977
sensitivity is %f 0.03214285714285714
specificity is %f 0.9956341490259383
accuracy is %f 0.9858372371718052
balanced accuracy is % 0.5138885030843977
Type1 Error is %f 119.0
Type2 Error is %f 271.0

 RandomForest :

Training Score for RandomForest :  99.41
Testing Score for RandomForest : 98.88
Classification report
               precision    recall  f1-score   support

           0       0.99      1.00      0.99     27257
           1       0.00      0.00      0.00       280

    accuracy                           0.99     27537
   macro avg       0.49      0.50      0.50     27537
weighted avg       0.98      0.99      0.98     27537

Confusion matrix
 [[27229    28]
 [  280     0]]
ROC AUC  : 0.4994863704736398
sensitivity is %f 0.0
specificity is %f 0.9989727409472796
accuracy is %f 0.9888150488433743
balanced accuracy is % 0.4994863704736398
Type1 Error is %f 28.0
Type2 Error is %f 280.0